name: Tests
on:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]
jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: install go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25

      - name: checkout
        uses: actions/checkout@v4

      - name: tests
        run: go test -race -v .
